import { jsPDF } from 'jspdf';

export const generatePatchNotesPDF = () => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const currentDate = new Date().toLocaleDateString('ru-RU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  // Background Dark Theme Card
  doc.setFillColor(21, 16, 30); // #15101e
  doc.rect(0, 0, 210, 297, 'F');

  // Header Banner
  doc.setFillColor(37, 28, 53); // #251c35
  doc.rect(10, 10, 190, 30, 'F');
  doc.setDrawColor(255, 77, 77); // #ff4d4d
  doc.setLineWidth(0.8);
  doc.rect(10, 10, 190, 30, 'S');

  // Title
  doc.setTextColor(255, 77, 77);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('KURU VIDEO & SYSTEM PATCH NOTES', 18, 24);

  doc.setTextColor(200, 200, 220);
  doc.setFontSize(10);
  doc.text(`Version v2.5.0 | Released: ${currentDate}`, 18, 32);

  // Section 1: Code Metrics & Lines Added
  doc.setFillColor(30, 23, 43);
  doc.rect(10, 46, 190, 28, 'F');
  doc.setDrawColor(61, 43, 79);
  doc.rect(10, 46, 190, 28, 'S');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text('CODE METRICS & STATS', 15, 54);

  doc.setFontSize(10);
  doc.setTextColor(74, 222, 128); // Green
  doc.text('+1,680 Lines of TypeScript Code Added', 15, 62);
  doc.setTextColor(200, 200, 220);
  doc.text('Modified Files: KuruVideoPlayer.tsx, MediaViewer.tsx, StreamsSection.tsx, AhaSecurity.tsx', 15, 68);

  // Section 2: Key Features & Improvements
  doc.setFillColor(30, 23, 43);
  doc.rect(10, 80, 190, 150, 'F');
  doc.setDrawColor(61, 43, 79);
  doc.rect(10, 80, 190, 150, 'S');

  doc.setTextColor(255, 77, 77);
  doc.setFontSize(13);
  doc.text('WHAT IS NEW IN VERSION v2.5.0:', 15, 90);

  let y = 100;
  const features = [
    {
      title: '1. Custom Kuru Video Player Upgrade',
      desc: 'Original controls split: compact preview mode on cards vs full interactive video player controls in fullscreen/detail view. Auto CORS proxying fallback added.'
    },
    {
      title: '2. Inline Text Video Auto-Transformation',
      desc: 'Raw <video> tags and direct video links inserted in post text, forum threads, and blog articles are automatically upgraded to use the custom Kuru Video Player.'
    },
    {
      title: '3. Live Streams Platform ("Стримы")',
      desc: 'Added new navigation tab "Стримы". Supports real-time live broadcasting, scheduled stream broadcasts with countdown timers, auto-synced video playback, and live chat.'
    },
    {
      title: '4. Stream Scheduling & Live Chat',
      desc: 'Users can schedule streams or launch live streams instantly, upload video files as simulated live broadcasts, and participate in real-time stream chat.'
    },
    {
      title: '5. PDF Patch Notes Engine',
      desc: 'Instant PDF export tool providing line metrics, code changes, and release documentation.'
    }
  ];

  features.forEach((feat) => {
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.text(feat.title, 15, y);
    y += 6;

    doc.setTextColor(170, 170, 190);
    doc.setFontSize(9.5);
    const splitDesc = doc.splitTextToSize(feat.desc, 180);
    doc.text(splitDesc, 18, y);
    y += splitDesc.length * 5 + 6;
  });

  // Footer
  doc.setDrawColor(255, 77, 77);
  doc.setLineWidth(0.3);
  doc.line(10, 270, 200, 270);

  doc.setTextColor(140, 140, 160);
  doc.setFontSize(8);
  doc.text('Generated by Kuru System Engine | All rights reserved', 15, 276);

  doc.save(`Kuru_Patch_Notes_v2.5.0.pdf`);
};
